# Generated by Django 5.2.17 on 2026-09-24 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lesson_start', 'Lesson started'), ('lesson_complete', 'Lesson completed'), ('assessment_start', 'Assessment started'), ('assessment_submit', 'Assessment submitted'), ('lab_submit', 'Lab submitted'), ('live_join', 'Live class joined'), ('material_open', 'Material opened'), ('video_watch', 'Video watched')], max_length=24)),
                ('subject', models.SlugField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.FloatField(default=0.0, help_text='e.g. seconds watched, percent score')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'kind'], name='analytics_l_user_id_888a5d_idx'), models.Index(fields=['subject', 'kind'], name='analytics_l_subject_9aec28_idx')],
            },
        ),
    ]
