# Generated by Django 5.2.17 on 2026-09-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('authority', models.CharField(blank=True, help_text='Exam board / ministry', max_length=160)),
                ('version', models.CharField(blank=True, help_text='Syllabus year/edition', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.SlugField(help_text='Subject slug, e.g. physics, electricity, math')),
                ('code', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='curriculum.framework')),
            ],
            options={
                'ordering': ['subject', 'order'],
                'unique_together': {('framework', 'subject', 'code', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable internal code, e.g. PHY-6.1', max_length=40)),
                ('reference', models.CharField(blank=True, help_text='Optional official syllabus code (kept blank unless verified)', max_length=80)),
                ('statement', models.TextField(help_text='What the learner can do, written as a can-do statement')),
                ('grade_min', models.PositiveSmallIntegerField(default=1)),
                ('grade_max', models.PositiveSmallIntegerField(default=12)),
                ('difficulty', models.FloatField(default=1000.0, help_text='Initial Elo difficulty estimate')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='curriculum.strand')),
            ],
            options={
                'ordering': ['strand', 'order'],
                'unique_together': {('strand', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial'), ('broader', 'Broader'), ('narrower', 'Narrower')], default='equivalent', max_length=12)),
                ('confidence', models.FloatField(default=0.8)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('from_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_out', to='curriculum.outcome')),
                ('to_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_in', to='curriculum.outcome')),
            ],
            options={
                'unique_together': {('from_outcome', 'to_outcome')},
            },
        ),
        migrations.CreateModel(
            name='OutcomeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(help_text='e.g. courses.Lesson', max_length=60)),
                ('target_id', models.PositiveIntegerField()),
                ('relation', models.CharField(choices=[('teaches', 'Teaches'), ('assesses', 'Assesses'), ('prerequisite', 'Prerequisite')], default='teaches', max_length=16)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='curriculum.outcome')),
            ],
            options={
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='curriculum__target__ade5f6_idx')],
                'unique_together': {('outcome', 'target_model', 'target_id', 'relation')},
            },
        ),
    ]
