# Generated by Django 5.2.17 on 2026-09-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Scheduled call length in minutes.'),
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Call window opens this time (participants can join a few minutes early).', null=True),
        ),
    ]
