# Generated by Django 5.2.17 on 2026-09-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lecture_duration',
            field=models.PositiveIntegerField(default=0, help_text='Lecture length in seconds'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lecture_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lecture_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=12),
        ),
    ]
