# Generated by Django 5.2.17 on 2026-09-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_lecture_duration_lesson_lecture_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('game', 'Game'), ('interactive', 'Interactive'), ('video', 'Video'), ('quiz', 'Quiz'), ('reading', 'Reading')], default='game', max_length=20),
        ),
    ]
