# Generated by Django 5.2.17 on 2026-09-24 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_lesson_lecture_duration_lesson_lecture_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('coding', 'Coding'), ('circuit', 'Circuit / Electronics'), ('physics', 'Physics'), ('science', 'Science')], default='coding', max_length=12)),
                ('subject', models.SlugField(blank=True, help_text='e.g. electricity, physics, computing')),
                ('grade_min', models.PositiveSmallIntegerField(default=1)),
                ('grade_max', models.PositiveSmallIntegerField(default=12)),
                ('prompt', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('blockly', 'Block-based'), ('python', 'Python (Pyodide)'), ('javascript', 'JavaScript'), ('none', 'Not code')], default='none', max_length=12)),
                ('starter_code', models.TextField(blank=True)),
                ('assets', models.JSONField(blank=True, default=dict)),
                ('tests', models.JSONField(blank=True, default=list)),
                ('solution', models.TextField(blank=True)),
                ('xp', models.PositiveIntegerField(default=20)),
                ('difficulty', models.FloatField(default=1000.0)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LabSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('passed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='labs.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['kind', 'subject', 'is_published'], name='labs_lab_kind_39bb4f_idx'),
        ),
    ]
