# Generated by Django 5.2.17 on 2026-09-24 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(default='en', max_length=10)),
                ('grade_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('ussd', 'USSD'), ('voice', 'Voice')], default='sms', max_length=8)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('body', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='gateway.phoneuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('ussd', 'USSD'), ('voice', 'Voice')], default='sms', max_length=8)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('choosing_subject', 'Choosing subject'), ('answering', 'Answering')], default='idle', max_length=20)),
                ('subject', models.SlugField(blank=True)),
                ('asked', models.JSONField(blank=True, default=list, help_text='Item ids already served')),
                ('score', models.PositiveIntegerField(default=0)),
                ('answered', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessment.item')),
                ('phone_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gateway.phoneuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
