# Generated by Django 5.2.17 on 2026-09-24 04:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_lesson_lecture_duration_lesson_lecture_file_and_more'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('subject', models.SlugField(blank=True)),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('practice', 'Practice'), ('diagnostic', 'Diagnostic'), ('exam', 'Exam')], default='quiz', max_length=12)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 = untimed')),
                ('pass_score', models.PositiveSmallIntegerField(default=60, help_text='Percent needed to pass')),
                ('max_items', models.PositiveSmallIntegerField(default=10, help_text='Items served per attempt')),
                ('adaptive', models.BooleanField(default=False)),
                ('grade_min', models.PositiveSmallIntegerField(default=1)),
                ('grade_max', models.PositiveSmallIntegerField(default=12)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='courses.course')),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='curriculum.framework')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('expired', 'Expired')], default='in_progress', max_length=12)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=1000.0)),
                ('served', models.JSONField(blank=True, default=list, help_text='Item ids served, in order')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=80)),
                ('score', models.FloatField(default=0.0)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('verify_hash', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='assessment.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.SlugField(blank=True, help_text='e.g. physics, electricity, math')),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice'), ('multi', 'Multiple select'), ('numeric', 'Numeric (with units)'), ('math', 'Math expression'), ('code', 'Code output'), ('order', 'Ordering'), ('match', 'Matching'), ('short', 'Short answer'), ('essay', 'Essay (manual)')], default='mcq', max_length=12)),
                ('prompt', models.TextField()),
                ('body', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('solution', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.FloatField(default=1000.0, help_text='Elo difficulty')),
                ('discrimination', models.FloatField(default=1.0)),
                ('grade_min', models.PositiveSmallIntegerField(default=1)),
                ('grade_max', models.PositiveSmallIntegerField(default=12)),
                ('language', models.CharField(default='en', max_length=10)),
                ('source', models.CharField(blank=True, help_text='Attribution / origin', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='courses.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('points', models.FloatField(default=1.0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessment.assessment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('correct', models.BooleanField(default=False)),
                ('awarded', models.FloatField(default=0.0)),
                ('max_points', models.FloatField(default=1.0)),
                ('needs_manual', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.attempt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['subject', 'kind', 'is_active'], name='assessment__subject_f1f2de_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['difficulty'], name='assessment__difficu_7648cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentitem',
            unique_together={('assessment', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('attempt', 'item')},
        ),
    ]
