"""Interactive lesson content (Brilliant-style guided discovery).

Each lesson is a sequence of steps rendered by
``frontend/src/lessons/InteractiveLesson.jsx``. Steps mix explanation with
hands-on manipulation, immediate feedback, hints and worked solutions — all
client-side so a lesson plays with zero signal.

Step schema
-----------
concept  {title, body, visual}
mcq      {prompt, options:[{text, correct, why}], hint, explain}
multi    {prompt, options:[{text, correct, why}], hint, explain}
numeric  {prompt, answer, tolerance, unit, hint, explain}
slider   {prompt, min, max, step, target, tolerance, unit, visual, hint, explain}
order    {prompt, items:[...], hint, explain}
match    {prompt, left:[...], right:[...], pairs:{left:right}, hint, explain}
plot     {mode:"numberline"|"xy", prompt, target, min, max, hint, explain}
circuit  {prompt, target_current, resistance, hint, explain}
free     {prompt, model, hint, explain}
"""

LESSONS = [
    # ------------------------------------------------------------------ MATH
    {
        "course_slug": "math",
        "module_title": "Fractions & Number Sense",
        "lesson_title": "Fractions: parts of a whole",
        "xp": 40,
        "steps": [
            {"type": "concept", "visual": "🍕",
             "title": "A fraction is a fair share",
             "body": "If you cut a pizza into 4 equal slices and take 1, you have one quarter — written 1/4. The bottom number (denominator) is how many equal parts the whole is cut into. The top number (numerator) is how many you take."},
            {"type": "slider", "visual": "fraction", "min": 1, "max": 8, "step": 1,
             "prompt": "Drag to cut the bar into equal parts. Make each part exactly 1/4 of the whole.",
             "target": 4, "tolerance": 0, "unit": "parts",
             "hint": "How many equal pieces make a whole quarter?",
             "explain": "Cutting the whole into 4 equal parts makes each part 1/4."},
            {"type": "mcq", "prompt": "Which fraction is the same amount as 1/2?",
             "options": [
                 {"text": "2/4", "correct": True, "why": "2 out of 4 equal parts is exactly half. 1/2 = 2/4."},
                 {"text": "1/4", "correct": False, "why": "1/4 is smaller than 1/2 — it is only one of four parts."},
                 {"text": "2/3", "correct": False, "why": "2/3 is larger than 1/2."},
             ],
             "hint": "Double both the top and bottom of 1/2.",
             "explain": "Multiplying the numerator and denominator by the same number gives an equivalent fraction."},
            {"type": "numeric", "prompt": "You eat 3 slices of a cake cut into 8 equal slices. What fraction did you eat? Enter the numerator if the denominator is 8.",
             "answer": 3, "tolerance": 0, "unit": "/8",
             "hint": "The number of slices you took is the numerator.",
             "explain": "3 slices out of 8 equal slices is 3/8."},
            {"type": "plot", "mode": "numberline", "prompt": "Tap the number line at the position of 3/4.",
             "target": 0.75, "min": 0, "max": 1,
             "hint": "3/4 is three quarters of the way from 0 to 1.",
             "explain": "3/4 sits at 0.75 — three of the four equal gaps."},
            {"type": "match", "prompt": "Match each fraction to the same amount written another way.",
             "left": ["1/2", "1/4", "3/4"],
             "right": ["25%", "50%", "75%"],
             "pairs": {"1/2": "50%", "1/4": "25%", "3/4": "75%"},
             "hint": "A half is 50 out of 100.",
             "explain": "Fractions, decimals and percentages are three languages for the same number."},
            {"type": "numeric", "prompt": "Add the fractions: 1/4 + 2/4 = ? Enter the numerator over 4.",
             "answer": 3, "tolerance": 0, "unit": "/4",
             "hint": "The parts are the same size, so just add the numerators.",
             "explain": "1/4 + 2/4 = 3/4 — same denominator, so add the tops."},
        ],
    },
    {
        "course_slug": "math",
        "module_title": "Algebra",
        "lesson_title": "Solve equations with a balance",
        "xp": 45,
        "steps": [
            {"type": "concept", "visual": "⚖️",
             "title": "An equation is a balanced scale",
             "body": "The equals sign means both sides weigh the same. Whatever you do to one side, do to the other — and it stays balanced. That is the whole secret to solving equations."},
            {"type": "slider", "visual": "balance", "min": 0, "max": 20, "step": 1,
             "prompt": "The left pan holds x + 3. The right pan holds 11. Find x so the scale balances.",
             "target": 8, "tolerance": 0, "unit": "",
             "hint": "What plus 3 equals 11?",
             "explain": "x = 8, because 8 + 3 = 11."},
            {"type": "mcq", "prompt": "To solve x + 5 = 12, what should you do to both sides?",
             "options": [
                 {"text": "Subtract 5", "correct": True, "why": "Subtracting 5 removes the +5 and leaves x alone."},
                 {"text": "Add 5", "correct": False, "why": "That would make x + 10 = 17 — no closer."},
                 {"text": "Multiply by 5", "correct": False, "why": "Multiplying changes the value, not the shape of the equation."},
             ],
             "hint": "Undo the +5 with its opposite.",
             "explain": "x + 5 − 5 = 12 − 5, so x = 7."},
            {"type": "numeric", "prompt": "Solve for x:  2x = 14",
             "answer": 7, "tolerance": 0, "unit": "",
             "hint": "2x means 2 times x. Undo the multiply by dividing.",
             "explain": "Divide both sides by 2: x = 7."},
            {"type": "numeric", "prompt": "Solve for x:  3x + 2 = 17",
             "answer": 5, "tolerance": 0, "unit": "",
             "hint": "First subtract 2 from both sides, then divide by 3.",
             "explain": "3x = 15, so x = 5."},
            {"type": "order", "prompt": "Put the steps to solve 2x + 4 = 12 in the right order.",
             "items": ["Write the equation: 2x + 4 = 12", "Subtract 4 from both sides: 2x = 8", "Divide both sides by 2: x = 4", "Check: 2(4) + 4 = 12 ✓"],
             "hint": "Undo addition before undoing multiplication.",
             "explain": "Work backwards through the operations: undo + and − first, then × and ÷."},
            {"type": "free", "prompt": "In your own words, why must you do the same thing to both sides of an equation?",
             "model": "Because the two sides are equal — like a balanced scale. Changing only one side would unbalance it, so to keep the equality true you apply the same operation to both sides.",
             "hint": "Think about the balance scale.",
             "explain": "Keeping both sides equal is what preserves the solution."},
        ],
    },
    # --------------------------------------------------------------- PHYSICS
    {
        "course_slug": "physics",
        "module_title": "Forces and Motion",
        "lesson_title": "Forces change motion",
        "xp": 45,
        "steps": [
            {"type": "concept", "visual": "🏀",
             "title": "Forces are pushes and pulls",
             "body": "A force can start something moving, stop it, speed it up, slow it down, or change its direction. If no force acts, an object keeps doing what it was already doing."},
            {"type": "slider", "visual": "force", "min": 0, "max": 20, "step": 1,
             "prompt": "Apply a force to the ball and watch how its motion changes. Set the force to 10 N.",
             "target": 10, "tolerance": 0, "unit": "N",
             "hint": "Drag the slider to 10.",
             "explain": "A bigger force gives a bigger change in motion. Here you applied 10 N."},
            {"type": "mcq", "prompt": "A book is sliding across a table and slowly stops. Why?",
             "options": [
                 {"text": "Friction is pushing against its motion", "correct": True, "why": "Friction is a force that opposes sliding, so it slows the book down."},
                 {"text": "It ran out of force", "correct": False, "why": "Objects don't 'hold' force — forces act between objects."},
                 {"text": "Gravity pulled it sideways", "correct": False, "why": "Gravity pulls down, not sideways."},
             ],
             "hint": "What happens when you rub your hands together?",
             "explain": "Friction acts opposite to motion and transfers energy, slowing the book."},
            {"type": "numeric", "prompt": "A 4 kg mass is pushed with a force of 20 N. Use F = m × a to find the acceleration (in m/s²).",
             "answer": 5, "tolerance": 0.01, "unit": "m/s²",
             "hint": "Rearrange: a = F ÷ m.",
             "explain": "a = 20 ÷ 4 = 5 m/s²."},
            {"type": "slider", "visual": "force", "min": 1, "max": 20, "step": 1,
             "prompt": "Same 4 kg mass. Drag the force until the acceleration is 3 m/s².",
             "target": 12, "tolerance": 0, "unit": "N",
             "hint": "F = m × a = 4 × 3.",
             "explain": "F = 4 × 3 = 12 N."},
            {"type": "order", "prompt": "Order the steps to calculate the force needed to accelerate a 2 kg ball at 6 m/s².",
             "items": ["Write the formula: F = m × a", "Substitute: F = 2 × 6", "Calculate: F = 12 N", "State units: newtons (N)"],
             "hint": "Formula, substitute, calculate, units.",
             "explain": "Always finish a physics calculation with the correct unit."},
            {"type": "mcq", "prompt": "Two equal forces push on a box from opposite sides. What happens?",
             "options": [
                 {"text": "The forces cancel — the box stays put", "correct": True, "why": "Equal and opposite forces balance, so there is no change in motion."},
                 {"text": "The box moves in both directions", "correct": False, "why": "It can only move one way at a time."},
                 {"text": "The forces add up and it shoots off", "correct": False, "why": "Opposite forces subtract, not add."},
             ],
             "hint": "Think about a tug-of-war that is perfectly even.",
             "explain": "Balanced forces produce no change in motion."},
        ],
    },
    {
        "course_slug": "physics",
        "module_title": "Forces and Motion",
        "lesson_title": "Speed and distance-time graphs",
        "xp": 45,
        "steps": [
            {"type": "concept", "visual": "🏃🏾",
             "title": "Speed tells you how fast distance changes",
             "body": "Speed = distance ÷ time. A bus covering 100 km in 2 hours travels at 50 km/h. On a distance-time graph, the steeper the line, the faster the object."},
            {"type": "numeric", "prompt": "A runner covers 400 m in 50 s. What is her speed in m/s?",
             "answer": 8, "tolerance": 0.01, "unit": "m/s",
             "hint": "Speed = distance ÷ time.",
             "explain": "400 ÷ 50 = 8 m/s."},
            {"type": "mcq", "prompt": "On a distance-time graph, a horizontal (flat) line means…",
             "options": [
                 {"text": "The object is stationary", "correct": True, "why": "Distance is not changing, so the object is at rest."},
                 {"text": "The object is moving fast", "correct": False, "why": "A fast object would have a steep line."},
                 {"text": "The object is going backwards", "correct": False, "why": "Going back would make distance decrease."},
             ],
             "hint": "What is happening to the distance over time?",
             "explain": "Flat means distance stays the same — the object has stopped."},
            {"type": "plot", "mode": "xy", "prompt": "A cyclist is at 20 m after 4 s. Tap that point on the graph (x = time, y = distance).",
             "target": [4, 20], "min": 0, "max": 25,
             "hint": "Go 4 across, 20 up.",
             "explain": "The point (4, 20) sits on a line with gradient 20 ÷ 4 = 5 m/s."},
            {"type": "mcq", "prompt": "Which line shows the faster object?",
             "options": [
                 {"text": "The steeper line", "correct": True, "why": "Steeper slope = more distance in the same time = faster."},
                 {"text": "The flatter line", "correct": False, "why": "Flatter means less distance covered, so slower."},
                 {"text": "They are always the same", "correct": False, "why": "Slope is what distinguishes speed."},
             ],
             "hint": "Slope = speed.",
             "explain": "Gradient of a distance-time graph equals speed."},
            {"type": "numeric", "prompt": "On a graph, a line rises 60 m in 12 s. What is the speed? (m/s)",
             "answer": 5, "tolerance": 0.01, "unit": "m/s",
             "hint": "Gradient = rise ÷ run.",
             "explain": "60 ÷ 12 = 5 m/s."},
        ],
    },
    # ----------------------------------------------------------- ELECTRICITY
    {
        "course_slug": "electricity",
        "module_title": "Circuits and Safety",
        "lesson_title": "Ohm's law in action",
        "xp": 50,
        "steps": [
            {"type": "concept", "visual": "⚡",
             "title": "Voltage pushes current through resistance",
             "body": "Think of voltage as pressure pushing water through a pipe. Resistance is how narrow the pipe is. More pressure pushes more current; a narrower pipe allows less. Ohm's law ties them together: V = I × R."},
            {"type": "circuit", "prompt": "Close the switch and adjust the supply until the current reads 2 A with a 3 Ω resistor.",
             "target_current": 2.0, "resistance": 3, "hint": "V = I × R = 2 × 3.",
             "explain": "V = 2 × 3 = 6 V. The ammeter shows 2 A."},
            {"type": "numeric", "prompt": "A 6 Ω resistor has 3 A flowing through it. What is the voltage? (V)",
             "answer": 18, "tolerance": 0.01, "unit": "V",
             "hint": "V = I × R.",
             "explain": "V = 3 × 6 = 18 V."},
            {"type": "numeric", "prompt": "A 12 V supply drives 4 A. What is the resistance? (Ω)",
             "answer": 3, "tolerance": 0.01, "unit": "Ω",
             "hint": "R = V ÷ I.",
             "explain": "R = 12 ÷ 4 = 3 Ω."},
            {"type": "mcq", "prompt": "If you increase the resistance but keep the voltage the same, the current will…",
             "options": [
                 {"text": "Decrease", "correct": True, "why": "I = V ÷ R, so a bigger R gives a smaller I."},
                 {"text": "Increase", "correct": False, "why": "That would need less resistance, not more."},
                 {"text": "Stay exactly the same", "correct": False, "why": "Current depends on resistance."},
             ],
             "hint": "Rearrange V = I × R for current.",
             "explain": "I = V / R, so current falls as resistance rises."},
            {"type": "order", "prompt": "Order the steps to find the current through a 5 Ω resistor across 20 V.",
             "items": ["Write Ohm's law: V = I × R", "Rearrange for current: I = V ÷ R", "Substitute: I = 20 ÷ 5", "Calculate: I = 4 A"],
             "hint": "Rearrange before you substitute.",
             "explain": "I = 20 ÷ 5 = 4 A."},
            {"type": "free", "prompt": "Why is a fuse useful? Explain in one or two sentences.",
             "model": "A fuse melts and breaks the circuit when the current gets too high, which stops overheating and prevents fires. It is a deliberate weak point that protects the wiring.",
             "hint": "What happens when too much current flows?",
             "explain": "A fuse protects against overload by breaking the circuit."},
        ],
    },
    {
        "course_slug": "electricity",
        "module_title": "Circuits and Safety",
        "lesson_title": "Series and parallel circuits",
        "xp": 50,
        "steps": [
            {"type": "concept", "visual": "🔀",
             "title": "One path or many paths?",
             "body": "In a series circuit the current has a single path — if one bulb breaks, the whole circuit stops. In a parallel circuit the current has several paths — one broken branch leaves the others lit. Homes are wired in parallel so one light switching off doesn't darken the house."},
            {"type": "mcq", "prompt": "Two bulbs are in series and one breaks. What happens to the other?",
             "options": [
                 {"text": "It goes out too", "correct": True, "why": "The single path is broken, so no current flows anywhere."},
                 {"text": "It gets brighter", "correct": False, "why": "It cannot get more current with a broken circuit."},
                 {"text": "Nothing changes", "correct": False, "why": "Series circuits have only one path."},
             ],
             "hint": "How many paths does the current have?",
             "explain": "Series = one path, so a break stops everything."},
            {"type": "mcq", "prompt": "Why are lights in a house wired in parallel?",
             "options": [
                 {"text": "So each light can be switched on and off independently", "correct": True, "why": "Parallel branches are independent — one can fail or switch off without affecting others."},
                 {"text": "Because it uses less wire", "correct": False, "why": "Parallel actually uses more wire."},
                 {"text": "Because bulbs are cheaper that way", "correct": False, "why": "Cost of bulbs is unrelated."},
             ],
             "hint": "What happens in your home when one bulb blows?",
             "explain": "Parallel circuits give each load its own independent path."},
            {"type": "numeric", "prompt": "Three identical 6 Ω resistors are in series. What is the total resistance? (Ω)",
             "answer": 18, "tolerance": 0.01, "unit": "Ω",
             "hint": "In series, resistances add up.",
             "explain": "6 + 6 + 6 = 18 Ω."},
            {"type": "match", "prompt": "Match each circuit type to its property.",
             "left": ["Series", "Parallel"],
             "right": ["One shared path", "Multiple independent paths"],
             "pairs": {"Series": "One shared path", "Parallel": "Multiple independent paths"},
             "hint": "Think about how many routes the current has.",
             "explain": "Series = one path; parallel = many."},
            {"type": "mcq", "prompt": "In a parallel circuit, the current splits between branches. What is true?",
             "options": [
                 {"text": "The total current equals the sum of the branch currents", "correct": True, "why": "Charge is conserved — what goes in must come out across the branches."},
                 {"text": "Each branch gets the full current", "correct": False, "why": "That would create extra charge from nowhere."},
                 {"text": "The current is zero in all branches", "correct": False, "why": "Current flows if the branches are complete."},
             ],
             "hint": "Charge cannot disappear.",
             "explain": "Current in = current out; the branches share the total."},
        ],
    },
    # ------------------------------------------------------------ COMPUTING
    {
        "course_slug": "computing",
        "module_title": "First Code",
        "lesson_title": "Variables and loops",
        "xp": 45,
        "steps": [
            {"type": "concept", "visual": "📦",
             "title": "A variable is a labelled box",
             "body": "A variable stores a value under a name so you can use it later. Think of a box labelled 'score' holding the number 10. You can change what is inside the box at any time."},
            {"type": "mcq", "prompt": "After these lines, what is inside score?\n\nscore = 5\nscore = score + 2",
             "options": [
                 {"text": "7", "correct": True, "why": "score + 2 takes the old 5, adds 2, and stores 7 back in score."},
                 {"text": "5", "correct": False, "why": "The second line replaces the value."},
                 {"text": "2", "correct": False, "why": "2 is added to the old value, not stored alone."},
             ],
             "hint": "Work through the lines in order.",
             "explain": "5 + 2 = 7, so score becomes 7."},
            {"type": "numeric", "prompt": "What does this print?\n\nx = 3\ny = 4\nprint(x * y)",
             "answer": 12, "tolerance": 0, "unit": "",
             "hint": "* means multiply.",
             "explain": "3 × 4 = 12."},
            {"type": "concept", "visual": "🔁",
             "title": "Loops repeat work",
             "body": "A loop runs the same instructions again and again. A 'for' loop that counts 1 to 5 saves you writing five separate lines. Repetition is where computers beat humans."},
            {"type": "numeric", "prompt": "How many times does the loop body run?\n\nfor i in range(1, 6):\n    print(i)",
             "answer": 5, "tolerance": 0, "unit": "",
             "hint": "range(1, 6) gives 1, 2, 3, 4, 5.",
             "explain": "It runs for i = 1, 2, 3, 4, 5 — five times."},
            {"type": "mcq", "prompt": "What is printed last by this loop?\n\nfor i in range(1, 4):\n    print(i * 10)",
             "options": [
                 {"text": "30", "correct": True, "why": "The last value is i = 3, and 3 × 10 = 30."},
                 {"text": "40", "correct": False, "why": "range(1, 4) stops at 3, not 4."},
                 {"text": "10", "correct": False, "why": "That is the first value, not the last."},
             ],
             "hint": "range stops before the end number.",
             "explain": "range(1, 4) gives 1, 2, 3; the last product is 30."},
            {"type": "order", "prompt": "Order the steps a loop takes each time round.",
             "items": ["Take the next value", "Run the loop body", "Check if more values remain", "Stop when the values run out"],
             "hint": "It checks before it stops.",
             "explain": "Each pass takes a value, runs the body, then checks whether to continue."},
            {"type": "free", "prompt": "Describe a job in your daily life that repeats, and how a loop could do it for you.",
             "model": "For example, greeting each student as they enter: instead of writing a greeting for every name, a loop takes each name from a list and prints 'Hello, name' — the same instruction repeated automatically.",
             "hint": "Look for anything you do over and over.",
             "explain": "Loops automate repetition — the same instruction applied to many items."},
        ],
    },
]
